# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
MD013:
  line_length: 600
MD022: false
MD024: false
MD033:
  allowed_elements:
    - p
    - strong
    - a
    - object
    - b
    - span
    - iframe
    - br
    - img
MD036: false
MD041: false
